PKG_NAME = pylibacl
PKG_VERS = 0.5.4
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://files.pythonhosted.org/packages/source/p/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

HOMEPAGE = http://pylibacl.k1024.org/
COMMENT  = This is a C extension module for Python which implements POSIX ACLs manipulation.
LICENSE  = LGPL 2.1

include ../../mk/spksrc.python-wheel.mk
