PKG_NAME = pyxattr
PKG_VERS = 0.7.1
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://pyxattr.k1024.org/downloads
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

HOMEPAGE = http://pyxattr.k1024.org/
COMMENT  = This is a C extension module for Python which implements extended attributes manipulation. 
LICENSE  = LGPL 2.1

include ../../mk/spksrc.python-wheel.mk
