PKG_NAME = psutil
PKG_VERS = 5.7.0
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://files.pythonhosted.org/packages/source/p/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

HOMEPAGE = https://github.com/giampaolo/psutil
COMMENT  = Cross-platform lib for process and system monitoring in Python.
LICENSE  = BSD 3-Clause License

include ../../mk/spksrc.python-wheel.mk
